# choose a sensor
sensor:
  file: hall_effect
  device: /dev/ttyACM0
  #for windows:
  #device: com7
# other sensors
#  MockSensor, for testing
#  SerialSensor, for a simple, lowspeed, lowcost cyclocomputer switch based sensor

# how long the race should be, in meters
race_distance: 200

# the circumference of the rollers, in millimeters
roller_circumference:
  red: 2108
  blue: 2108

#the title of the window and label displayed on the track during races
title: OpenSprints

#the measurement system for velocity: standard or metric
units: standard
#units: metric

#the speed at which the speed vs. time graph maxes out
graph_max: 90 
