# choose a sensor
# which sensor type you will be using
# arduino - the main sensor type for racing
# mock_arduino - for debugging without hall effect boards
# mock - for debugging without a sensor
sensor:
  type: arduino
# Device is where the UBW is located in your system, usually:
#   Mac OS X: /dev/tty.usbmodem0000103D1
#   Linux: /dev/ttyACM0
#   Windows: com6
  device: /dev/ttyUSB0

# how long the race should be, in meters
race_distance: 200

# the size of each roller, in millimeters
roller_circumference: 2108

#the title displayed
title: OpenSprints

#the measurement system displayed: standard or metric
units: standard
#units: metric


# The list of racers' colors. Supports from 1-4 racers.
# Provide as many colors as you want racers.
# Can be in any format shoes understands:
# e.g.: "red" or "#FF0000" or "rgb(255,0,0)"
bikes:
- red
- blue
