# choose a sensor
sensor:
  file: mock
  device: /dev/ttyACM0
  #for windows:
  #device: com7
# other sensors
#  MockSensor, for testing
#  SerialSensor, for a simple, lowspeed, lowcost cyclocomputer switch based sensor

# how long the race should be, in meters
race_distance: 50

# the size of each wheel, in millimeters
wheel_circumference:
  red: 885
  blue: 885

#the title of the window and label displayed on the track during races
title: OpenSprints
